# Generated by Django 5.0.2 on 2024-03-01 15:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Data Criação')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Data Atualização')),
                ('executon_date', models.DateTimeField()),
                ('execution_data', models.TextField(blank=True, null=True)),
                ('url_scraping', models.CharField(max_length=50)),
                ('request_data', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
