# Generated by Django 5.0.2 on 2024-03-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0002_alter_execution_executon_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='execution',
            old_name='executon_date',
            new_name='execution_date',
        ),
        migrations.AlterField(
            model_name='execution',
            name='url_scraping',
            field=models.CharField(choices=[('http://www.infraestrutura.mg.gov.br/ajuda/page/44-preco-setop', 'SETO'), ('http://www.infraestrutura.mg.gov.br/component/gmg/page/102-c', 'INFRA MG'), ('https://pncp.gov.br/app/editais?q=&&status=recebendo_proposta&pagina=1', 'PNCP'), ('https://licitacoes.caixa.gov.br/', 'CAIXA')], max_length=200),
        ),
    ]
