# Generated by Django 5.0.2 on 2024-03-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_scraping', '0003_rename_executon_date_execution_execution_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='execution',
            name='url_scraping',
            field=models.CharField(choices=[('http://www.infraestrutura.mg.gov.br/ajuda/page/44-preco-setop', 'SETOP'), ('http://www.infraestrutura.mg.gov.br/component/gmg/page/102-c', 'INFRA MG'), ('https://pncp.gov.br/app/editais?q=&&status=recebendo_proposta&pagina=1', 'PNCP'), ('https://licitacoes.caixa.gov.br/', 'CAIXA')], max_length=200),
        ),
    ]
